name: box
homepage: https://github.com/stijnvanbael/box
version: 0.2.3
description: A fluent Dart persistence API inspired by SQL
environment:
  sdk: ">=2.3.0 <3.0.0"
dependencies:
  io: ^0.3.3
  meta: ^1.1.8
  collection: ^1.14.11
  reflective: ^0.1.9
  mongo_dart: ^0.4.0
  inflection2: ^0.4.2
  firebase: ^7.2.1
dev_dependencies:
  test: any
