name: box
author: Stijn Van Bael <stijn.van.bael@appify.be>
homepage: https://github.com/stijnvanbael/box
version: 0.0.11
description: A fluent Dart persistence API inspired by SQL
environment:
  sdk: ">=1.10.0"
dependencies:
  io: ">=0.1.0-git <0.2.0-git"
  exportable: ">=0.1.0 <0.2.0"
  collection: ">=1.0.0 <2.0.0"
  reflective: ">=0.0.0 <0.1.0"
dev_dependencies:
  unittest: any
