name: box
homepage: https://github.com/stijnvanbael/box
version: 0.2.4
description: A fluent Dart persistence API inspired by SQL
environment:
  sdk: ">=2.3.0 <3.0.0"
dependencies:
  io: ^0.3.3
  meta: ^1.1.8
  collection: ^1.14.11
  mongo_dart: ^0.4.0
  inflection2: ^0.4.2
  googleapis_auth: ^0.2.11
  http: ^0.12.1
dev_dependencies:
  test: ^1.6.0
  build_runner: ^1.10.0
  box_generator:
    path: ../box_generator
