name: box
homepage: https://github.com/stijnvanbael/box
version: 0.3.3+2
description: A fluent Dart persistence API inspired by SQL that supports PostgreSQL, MongoDB, simple file and in-memory storage.
environment:
  sdk: ">=2.12.0 <3.0.0"
dependencies:
  io: ^1.0.0
  meta: ^1.3.0
  collection: ^1.16.0
  recase: ^4.0.0
  mongo_dart: ^0.7.4+1
  postgres: ^2.3.2
  http: ^0.13.4
  googleapis_auth: ^1.1.0

dev_dependencies:
  lints: ^1.0.0
  test: ^1.16.0
  build_runner: ^2.1.10
  box_generator: ^0.3.3+2
