name: box
author: Stijn Van Bael <stijn.van.bael@appify.be>
homepage: https://github.com/stijnvanbael/box
version: 0.1.1+1
description: A fluent Dart persistence API inspired by SQL
environment:
  sdk: ">=2.0.0 <3.0.0"
dependencies:
  io: ^0.3.3
  collection: ^1.14.11
  reflective: ^0.1.1
dev_dependencies:
  test: any
