name: box
homepage: https://github.com/stijnvanbael/box
version: 0.3.0+2
description: A fluent Dart persistence API inspired by SQL that supports PostgreSQL, MongoDB, simple file and in-memory storage.
environment:
  sdk: ">=2.2.2 <3.0.0"
dependencies:
  io: ^0.3.3
  meta: ^1.1.8
  collection: ^1.14.11
  inflection2: ^0.4.2
  recase: ^3.0.0
  mongo_dart: ^0.4.3
  postgres: ^2.1.1
  http: ^0.12.1
  googleapis_auth: ^0.2.11

dev_dependencies:
  test: ^1.6.0
  build_runner: ^1.10.4
  box_generator: ^0.3.0+2
